# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps: 
- task: Ant@1
  inputs:
    buildFile: 'build.xml'
    options: 
    targets: 'compile'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'  

- task: dependency-check-build-task@6
  inputs:
    projectName: 'SampleWebApp'
    scanPath: '.'
    format: 'HTML' 

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'prajktamhapsekar829'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'prajktamhapsekar829'
    cliProjectName: 'SampleWebApp'
    cliSources: '.'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.java.binaries=.

- task: SonarCloudAnalyze@1 
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300' 

- task: Ant@1
  inputs:
    buildFile: 'build.xml'
    options: 
    targets: 'war'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion' 

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'tomcat-devsecops-connection'
    sourceFolder: '/home/vsts/work/1/s/dest'
    contents: '**/*.war'
    targetFolder: '/var/lib/tomcat9/webapps'
    readyTimeout: '20000' 

- task: owaspzap@1
  inputs:
    threshold: '300'
    scantype: 'targetedScan'
    url: 'http://13.235.0.50:8080//SampleWebApp'
    provideCustomContext: true
    contextPath: '/SampleWebApp'